// Curated lists for the profile language/timezone pickers (searchable dropdowns).

export interface Locale {
  code: string;
  name: string;
}

export const LOCALES: Locale[] = [
  { code: "en-US", name: "English (United States)" },
  { code: "en-GB", name: "English (United Kingdom)" },
  { code: "en-AU", name: "English (Australia)" },
  { code: "en-CA", name: "English (Canada)" },
  { code: "en-NZ", name: "English (New Zealand)" },
  { code: "en-IE", name: "English (Ireland)" },
  { code: "en-ZA", name: "English (South Africa)" },
  { code: "en-SG", name: "English (Singapore)" },
  { code: "en-PH", name: "English (Philippines)" },
  { code: "de-DE", name: "German (Germany)" },
  { code: "de-AT", name: "German (Austria)" },
  { code: "de-CH", name: "German (Switzerland)" },
  { code: "fr-FR", name: "French (France)" },
  { code: "fr-BE", name: "French (Belgium)" },
  { code: "fr-CA", name: "French (Canada)" },
  { code: "es-ES", name: "Spanish (Spain)" },
  { code: "es-MX", name: "Spanish (Mexico)" },
  { code: "es-AR", name: "Spanish (Argentina)" },
  { code: "es-CO", name: "Spanish (Colombia)" },
  { code: "es-CL", name: "Spanish (Chile)" },
  { code: "pt-BR", name: "Portuguese (Brazil)" },
  { code: "pt-PT", name: "Portuguese (Portugal)" },
  { code: "it-IT", name: "Italian (Italy)" },
  { code: "nl-NL", name: "Dutch (Netherlands)" },
  { code: "nl-BE", name: "Dutch (Belgium)" },
  { code: "ru-RU", name: "Russian (Russia)" },
  { code: "uk-UA", name: "Ukrainian (Ukraine)" },
  { code: "pl-PL", name: "Polish (Poland)" },
  { code: "cs-CZ", name: "Czech (Czechia)" },
  { code: "sk-SK", name: "Slovak (Slovakia)" },
  { code: "ro-RO", name: "Romanian (Romania)" },
  { code: "hu-HU", name: "Hungarian (Hungary)" },
  { code: "bg-BG", name: "Bulgarian (Bulgaria)" },
  { code: "el-GR", name: "Greek (Greece)" },
  { code: "sv-SE", name: "Swedish (Sweden)" },
  { code: "nb-NO", name: "Norwegian (Norway)" },
  { code: "da-DK", name: "Danish (Denmark)" },
  { code: "fi-FI", name: "Finnish (Finland)" },
  { code: "et-EE", name: "Estonian (Estonia)" },
  { code: "lv-LV", name: "Latvian (Latvia)" },
  { code: "lt-LT", name: "Lithuanian (Lithuania)" },
  { code: "tr-TR", name: "Turkish (Turkey)" },
  { code: "he-IL", name: "Hebrew (Israel)" },
  { code: "ar-SA", name: "Arabic (Saudi Arabia)" },
  { code: "ar-AE", name: "Arabic (UAE)" },
  { code: "ar-EG", name: "Arabic (Egypt)" },
  { code: "fa-IR", name: "Persian (Iran)" },
  { code: "hi-IN", name: "Hindi (India)" },
  { code: "id-ID", name: "Indonesian (Indonesia)" },
  { code: "ms-MY", name: "Malay (Malaysia)" },
  { code: "th-TH", name: "Thai (Thailand)" },
  { code: "vi-VN", name: "Vietnamese (Vietnam)" },
  { code: "ja-JP", name: "Japanese (Japan)" },
  { code: "ko-KR", name: "Korean (South Korea)" },
  { code: "zh-CN", name: "Chinese (Simplified, China)" },
  { code: "zh-TW", name: "Chinese (Traditional, Taiwan)" },
  { code: "zh-HK", name: "Chinese (Hong Kong)" },
];

export const TIMEZONES: string[] = [
  "America/New_York", "America/Chicago", "America/Denver", "America/Los_Angeles",
  "America/Phoenix", "America/Anchorage", "America/Toronto", "America/Vancouver",
  "America/Mexico_City", "America/Sao_Paulo", "America/Argentina/Buenos_Aires",
  "America/Bogota", "America/Santiago", "America/Lima",
  "Europe/London", "Europe/Dublin", "Europe/Lisbon", "Europe/Madrid", "Europe/Paris",
  "Europe/Brussels", "Europe/Amsterdam", "Europe/Berlin", "Europe/Zurich", "Europe/Vienna",
  "Europe/Rome", "Europe/Copenhagen", "Europe/Oslo", "Europe/Stockholm", "Europe/Helsinki",
  "Europe/Tallinn", "Europe/Riga", "Europe/Vilnius", "Europe/Warsaw", "Europe/Prague",
  "Europe/Bratislava", "Europe/Budapest", "Europe/Bucharest", "Europe/Sofia", "Europe/Athens",
  "Europe/Kyiv", "Europe/Moscow", "Europe/Istanbul",
  "Africa/Cairo", "Africa/Johannesburg", "Africa/Lagos", "Africa/Nairobi",
  "Asia/Jerusalem", "Asia/Riyadh", "Asia/Dubai", "Asia/Tehran", "Asia/Karachi",
  "Asia/Kolkata", "Asia/Dhaka", "Asia/Bangkok", "Asia/Jakarta", "Asia/Singapore",
  "Asia/Kuala_Lumpur", "Asia/Manila", "Asia/Ho_Chi_Minh", "Asia/Hong_Kong",
  "Asia/Shanghai", "Asia/Taipei", "Asia/Tokyo", "Asia/Seoul",
  "Australia/Sydney", "Australia/Melbourne", "Australia/Perth",
  "Pacific/Auckland", "UTC",
];
